// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'third_party/openac_mobile_app.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 1810054927;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'mopro_flutter_bindings',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<String> openacMobileAppBenchmarkResultsFormatSize({
    required BigInt bytes,
  });

  Future<String> openacMobileAppBuildSmtFromSnapshot({
    required String snapshotJson,
  });

  Future<SmtProof> openacMobileAppCreateSmtProof({
    required String snapshotJson,
    required String keyHex,
  });

  Future<SmtProof> openacMobileAppCreateSmtProofFromGz({
    required List<int> gzData,
    required String keyHex,
  });

  Future<String> openacMobileAppGenerateCertChainRs4096Input({
    required String certb64,
    required String signedResponse,
    required String tbs,
    required String issuerCertPath,
    String? smtSnapshotPath,
    required String outputDir,
  });

  Future<void> openacMobileAppInitApp();

  Future<bool> openacMobileAppLinkVerify({required String documentsPath});

  Future<String> openacMobileAppMoproHelloWorld();

  Future<ProofResult> openacMobileAppProveCertChainRs4096({
    required String documentsPath,
  });

  Future<ProofResult> openacMobileAppProveDeviceSigRs2048({
    required String documentsPath,
  });

  Future<BenchmarkResults> openacMobileAppRunCompleteBenchmark({
    required String documentsPath,
  });

  Future<String> openacMobileAppSetupKeys({required String documentsPath});

  Future<SmtCircuitInputs> openacMobileAppSmtProofToCircuitInputs({
    required SmtProof proof,
    required int depth,
  });

  Future<bool> openacMobileAppVerifyCertChainRs4096({
    required String documentsPath,
  });

  Future<bool> openacMobileAppVerifyDeviceSigRs2048({
    required String documentsPath,
  });

  Future<bool> openacMobileAppVerifySmtProof({
    required SmtProof proof,
    required String expectedRoot,
  });

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ZkProofError;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ZkProofError;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_ZkProofErrorPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> openacMobileAppBenchmarkResultsFormatSize({
    required BigInt bytes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(bytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kOpenacMobileAppBenchmarkResultsFormatSizeConstMeta,
        argValues: [bytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kOpenacMobileAppBenchmarkResultsFormatSizeConstMeta =>
      const TaskConstMeta(
        debugName: "benchmark_results_format_size",
        argNames: ["bytes"],
      );

  @override
  Future<String> openacMobileAppBuildSmtFromSnapshot({
    required String snapshotJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(snapshotJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kOpenacMobileAppBuildSmtFromSnapshotConstMeta,
        argValues: [snapshotJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kOpenacMobileAppBuildSmtFromSnapshotConstMeta =>
      const TaskConstMeta(
        debugName: "build_smt_from_snapshot",
        argNames: ["snapshotJson"],
      );

  @override
  Future<SmtProof> openacMobileAppCreateSmtProof({
    required String snapshotJson,
    required String keyHex,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(snapshotJson, serializer);
          sse_encode_String(keyHex, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_smt_proof,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkProofError,
        ),
        constMeta: kOpenacMobileAppCreateSmtProofConstMeta,
        argValues: [snapshotJson, keyHex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kOpenacMobileAppCreateSmtProofConstMeta =>
      const TaskConstMeta(
        debugName: "create_smt_proof",
        argNames: ["snapshotJson", "keyHex"],
      );

  @override
  Future<SmtProof> openacMobileAppCreateSmtProofFromGz({
    required List<int> gzData,
    required String keyHex,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(gzData, serializer);
          sse_encode_String(keyHex, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_smt_proof,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkProofError,
        ),
        constMeta: kOpenacMobileAppCreateSmtProofFromGzConstMeta,
        argValues: [gzData, keyHex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kOpenacMobileAppCreateSmtProofFromGzConstMeta =>
      const TaskConstMeta(
        debugName: "create_smt_proof_from_gz",
        argNames: ["gzData", "keyHex"],
      );

  @override
  Future<String> openacMobileAppGenerateCertChainRs4096Input({
    required String certb64,
    required String signedResponse,
    required String tbs,
    required String issuerCertPath,
    String? smtSnapshotPath,
    required String outputDir,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(certb64, serializer);
          sse_encode_String(signedResponse, serializer);
          sse_encode_String(tbs, serializer);
          sse_encode_String(issuerCertPath, serializer);
          sse_encode_opt_String(smtSnapshotPath, serializer);
          sse_encode_String(outputDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkProofError,
        ),
        constMeta: kOpenacMobileAppGenerateCertChainRs4096InputConstMeta,
        argValues: [
          certb64,
          signedResponse,
          tbs,
          issuerCertPath,
          smtSnapshotPath,
          outputDir,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kOpenacMobileAppGenerateCertChainRs4096InputConstMeta =>
      const TaskConstMeta(
        debugName: "generate_cert_chain_rs4096_input",
        argNames: [
          "certb64",
          "signedResponse",
          "tbs",
          "issuerCertPath",
          "smtSnapshotPath",
          "outputDir",
        ],
      );

  @override
  Future<void> openacMobileAppInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kOpenacMobileAppInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kOpenacMobileAppInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<bool> openacMobileAppLinkVerify({required String documentsPath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(documentsPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkProofError,
        ),
        constMeta: kOpenacMobileAppLinkVerifyConstMeta,
        argValues: [documentsPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kOpenacMobileAppLinkVerifyConstMeta => const TaskConstMeta(
    debugName: "link_verify",
    argNames: ["documentsPath"],
  );

  @override
  Future<String> openacMobileAppMoproHelloWorld() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kOpenacMobileAppMoproHelloWorldConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kOpenacMobileAppMoproHelloWorldConstMeta =>
      const TaskConstMeta(debugName: "mopro_hello_world", argNames: []);

  @override
  Future<ProofResult> openacMobileAppProveCertChainRs4096({
    required String documentsPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(documentsPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_proof_result,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkProofError,
        ),
        constMeta: kOpenacMobileAppProveCertChainRs4096ConstMeta,
        argValues: [documentsPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kOpenacMobileAppProveCertChainRs4096ConstMeta =>
      const TaskConstMeta(
        debugName: "prove_cert_chain_rs4096",
        argNames: ["documentsPath"],
      );

  @override
  Future<ProofResult> openacMobileAppProveDeviceSigRs2048({
    required String documentsPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(documentsPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_proof_result,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkProofError,
        ),
        constMeta: kOpenacMobileAppProveDeviceSigRs2048ConstMeta,
        argValues: [documentsPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kOpenacMobileAppProveDeviceSigRs2048ConstMeta =>
      const TaskConstMeta(
        debugName: "prove_device_sig_rs2048",
        argNames: ["documentsPath"],
      );

  @override
  Future<BenchmarkResults> openacMobileAppRunCompleteBenchmark({
    required String documentsPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(documentsPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_benchmark_results,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkProofError,
        ),
        constMeta: kOpenacMobileAppRunCompleteBenchmarkConstMeta,
        argValues: [documentsPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kOpenacMobileAppRunCompleteBenchmarkConstMeta =>
      const TaskConstMeta(
        debugName: "run_complete_benchmark",
        argNames: ["documentsPath"],
      );

  @override
  Future<String> openacMobileAppSetupKeys({required String documentsPath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(documentsPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkProofError,
        ),
        constMeta: kOpenacMobileAppSetupKeysConstMeta,
        argValues: [documentsPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kOpenacMobileAppSetupKeysConstMeta =>
      const TaskConstMeta(debugName: "setup_keys", argNames: ["documentsPath"]);

  @override
  Future<SmtCircuitInputs> openacMobileAppSmtProofToCircuitInputs({
    required SmtProof proof,
    required int depth,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_smt_proof(proof, serializer);
          sse_encode_u_32(depth, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_smt_circuit_inputs,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkProofError,
        ),
        constMeta: kOpenacMobileAppSmtProofToCircuitInputsConstMeta,
        argValues: [proof, depth],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kOpenacMobileAppSmtProofToCircuitInputsConstMeta =>
      const TaskConstMeta(
        debugName: "smt_proof_to_circuit_inputs",
        argNames: ["proof", "depth"],
      );

  @override
  Future<bool> openacMobileAppVerifyCertChainRs4096({
    required String documentsPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(documentsPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkProofError,
        ),
        constMeta: kOpenacMobileAppVerifyCertChainRs4096ConstMeta,
        argValues: [documentsPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kOpenacMobileAppVerifyCertChainRs4096ConstMeta =>
      const TaskConstMeta(
        debugName: "verify_cert_chain_rs4096",
        argNames: ["documentsPath"],
      );

  @override
  Future<bool> openacMobileAppVerifyDeviceSigRs2048({
    required String documentsPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(documentsPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkProofError,
        ),
        constMeta: kOpenacMobileAppVerifyDeviceSigRs2048ConstMeta,
        argValues: [documentsPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kOpenacMobileAppVerifyDeviceSigRs2048ConstMeta =>
      const TaskConstMeta(
        debugName: "verify_device_sig_rs2048",
        argNames: ["documentsPath"],
      );

  @override
  Future<bool> openacMobileAppVerifySmtProof({
    required SmtProof proof,
    required String expectedRoot,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_smt_proof(proof, serializer);
          sse_encode_String(expectedRoot, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kOpenacMobileAppVerifySmtProofConstMeta,
        argValues: [proof, expectedRoot],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kOpenacMobileAppVerifySmtProofConstMeta =>
      const TaskConstMeta(
        debugName: "verify_smt_proof",
        argNames: ["proof", "expectedRoot"],
      );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ZkProofError =>
      wire.rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkProofError;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ZkProofError =>
      wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkProofError;

  @protected
  ZkProofError
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkProofError(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ZkProofErrorImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ZkProofError
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkProofError(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ZkProofErrorImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  BenchmarkResults dco_decode_benchmark_results(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return BenchmarkResults(
      setupMs: dco_decode_u_64(arr[0]),
      proveMs: dco_decode_u_64(arr[1]),
      verifyMs: dco_decode_u_64(arr[2]),
      provingKeyBytes: dco_decode_u_64(arr[3]),
      verifyingKeyBytes: dco_decode_u_64(arr[4]),
      proofBytes: dco_decode_u_64(arr[5]),
      witnessBytes: dco_decode_u_64(arr[6]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  SmtProof dco_decode_box_autoadd_smt_proof(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_smt_proof(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_String(raw);
  }

  @protected
  ProofResult dco_decode_proof_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ProofResult(
      proveMs: dco_decode_u_64(arr[0]),
      proofSizeBytes: dco_decode_u_64(arr[1]),
    );
  }

  @protected
  SmtCircuitInputs dco_decode_smt_circuit_inputs(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return SmtCircuitInputs(
      smtRoot: dco_decode_String(arr[0]),
      serialNumber: dco_decode_String(arr[1]),
      smtSiblings: dco_decode_list_String(arr[2]),
      smtOldKey: dco_decode_String(arr[3]),
      smtOldValue: dco_decode_String(arr[4]),
      smtIsOld0: dco_decode_String(arr[5]),
    );
  }

  @protected
  SmtProof dco_decode_smt_proof(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return SmtProof(
      root: dco_decode_String(arr[0]),
      siblings: dco_decode_list_String(arr[1]),
      entry: dco_decode_list_String(arr[2]),
      matchingEntry: dco_decode_opt_list_String(arr[3]),
      membership: dco_decode_bool(arr[4]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  ZkProofError
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkProofError(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ZkProofErrorImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ZkProofError
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkProofError(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ZkProofErrorImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  BenchmarkResults sse_decode_benchmark_results(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_setupMs = sse_decode_u_64(deserializer);
    var var_proveMs = sse_decode_u_64(deserializer);
    var var_verifyMs = sse_decode_u_64(deserializer);
    var var_provingKeyBytes = sse_decode_u_64(deserializer);
    var var_verifyingKeyBytes = sse_decode_u_64(deserializer);
    var var_proofBytes = sse_decode_u_64(deserializer);
    var var_witnessBytes = sse_decode_u_64(deserializer);
    return BenchmarkResults(
      setupMs: var_setupMs,
      proveMs: var_proveMs,
      verifyMs: var_verifyMs,
      provingKeyBytes: var_provingKeyBytes,
      verifyingKeyBytes: var_verifyingKeyBytes,
      proofBytes: var_proofBytes,
      witnessBytes: var_witnessBytes,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  SmtProof sse_decode_box_autoadd_smt_proof(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_smt_proof(deserializer));
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ProofResult sse_decode_proof_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_proveMs = sse_decode_u_64(deserializer);
    var var_proofSizeBytes = sse_decode_u_64(deserializer);
    return ProofResult(
      proveMs: var_proveMs,
      proofSizeBytes: var_proofSizeBytes,
    );
  }

  @protected
  SmtCircuitInputs sse_decode_smt_circuit_inputs(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_smtRoot = sse_decode_String(deserializer);
    var var_serialNumber = sse_decode_String(deserializer);
    var var_smtSiblings = sse_decode_list_String(deserializer);
    var var_smtOldKey = sse_decode_String(deserializer);
    var var_smtOldValue = sse_decode_String(deserializer);
    var var_smtIsOld0 = sse_decode_String(deserializer);
    return SmtCircuitInputs(
      smtRoot: var_smtRoot,
      serialNumber: var_serialNumber,
      smtSiblings: var_smtSiblings,
      smtOldKey: var_smtOldKey,
      smtOldValue: var_smtOldValue,
      smtIsOld0: var_smtIsOld0,
    );
  }

  @protected
  SmtProof sse_decode_smt_proof(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_root = sse_decode_String(deserializer);
    var var_siblings = sse_decode_list_String(deserializer);
    var var_entry = sse_decode_list_String(deserializer);
    var var_matchingEntry = sse_decode_opt_list_String(deserializer);
    var var_membership = sse_decode_bool(deserializer);
    return SmtProof(
      root: var_root,
      siblings: var_siblings,
      entry: var_entry,
      matchingEntry: var_matchingEntry,
      membership: var_membership,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkProofError(
    ZkProofError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ZkProofErrorImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkProofError(
    ZkProofError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ZkProofErrorImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_benchmark_results(
    BenchmarkResults self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.setupMs, serializer);
    sse_encode_u_64(self.proveMs, serializer);
    sse_encode_u_64(self.verifyMs, serializer);
    sse_encode_u_64(self.provingKeyBytes, serializer);
    sse_encode_u_64(self.verifyingKeyBytes, serializer);
    sse_encode_u_64(self.proofBytes, serializer);
    sse_encode_u_64(self.witnessBytes, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_smt_proof(
    SmtProof self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_smt_proof(self, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_String(
    List<String>? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_String(self, serializer);
    }
  }

  @protected
  void sse_encode_proof_result(ProofResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.proveMs, serializer);
    sse_encode_u_64(self.proofSizeBytes, serializer);
  }

  @protected
  void sse_encode_smt_circuit_inputs(
    SmtCircuitInputs self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.smtRoot, serializer);
    sse_encode_String(self.serialNumber, serializer);
    sse_encode_list_String(self.smtSiblings, serializer);
    sse_encode_String(self.smtOldKey, serializer);
    sse_encode_String(self.smtOldValue, serializer);
    sse_encode_String(self.smtIsOld0, serializer);
  }

  @protected
  void sse_encode_smt_proof(SmtProof self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.root, serializer);
    sse_encode_list_String(self.siblings, serializer);
    sse_encode_list_String(self.entry, serializer);
    sse_encode_opt_list_String(self.matchingEntry, serializer);
    sse_encode_bool(self.membership, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class ZkProofErrorImpl extends RustOpaque implements ZkProofError {
  // Not to be used by end users
  ZkProofErrorImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ZkProofErrorImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_ZkProofError,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_ZkProofError,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_ZkProofErrorPtr,
  );
}
