[package]
name = "ecdsa-spartan2-jwt"
version = "0.0.1"
edition = "2021"

[lib]
name = "ecdsa_spartan2"
path = "src/lib.rs"

[[bin]]
name = "ecdsa-spartan2-jwt"
path = "src/main.rs"

[dependencies]
spartan2 = { git = "https://github.com/0xVikasRushi/Spartan2.git", branch = "openac-sdk", default-features = false }
circom-scotia = { git = "https://github.com/0xVikasRushi/circom-scotia", branch = "feat/spartan2", default-features = false }

bellpepper = "0.4.0"
bellpepper-core = "0.4.0"
ff = { version = "0.13.0", features = ["derive"] }
serde = { version = "1.0.219", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "time"] }
bincode = "1.3.3"

[profile.release]
debug = true
