/**
 * Generate P-256 Poseidon constants in circom format.
 * Produces: circuits/components/poseidon_p256_constants.circom
 *
 * Usage: node scripts/gen_poseidon_p256_constants.mjs
 */

import { writeFileSync } from "fs";
import { Field } from "@noble/curves/abstract/modular";
import { grainGenConstants } from "@noble/curves/abstract/poseidon";

// circom's secq256r1 prime is the P-256 BASE FIELD (not the scalar field)
const BASE_FIELD_ORDER =
  0xffffffff00000001000000000000000000000000ffffffffffffffffffffffffn;
const Fp = Field(BASE_FIELD_ORDER);

const ROUNDS_FULL = 8;

function toDecimal(n) {
  return n.toString(10);
}

function generateCircomConstants() {
  const configs = [
    { t: 3, rp: 57 }, // Poseidon(2) — used by SMTHash2(L, R)
    { t: 4, rp: 56 }, // Poseidon(3) — used by SMTHash1(key, value) = Poseidon(key, value, 1)
  ];

  let circom = `// P-256 (secp256r1) Poseidon round constants and MDS matrices.
// Auto-generated by gen_poseidon_p256_constants.mjs
// Field: P-256 base field 0xFFFFFFFF00000001000000000000000000000000FFFFFFFFFFFFFFFFFFFFFFFF
// Parameters: sbox=x^5, RF=8
//   t=3: RP=57 (for Poseidon(2))
//   t=4: RP=56 (for Poseidon(3))

pragma circom 2.2.3;

`;

  for (const { t, rp } of configs) {
    const { roundConstants, mds } = grainGenConstants({
      Fp,
      t,
      roundsFull: ROUNDS_FULL,
      roundsPartial: rp,
    });

    const totalRounds = ROUNDS_FULL + rp;

    // Flatten round constants: C[round * t + j]
    circom += `function POSEIDON_P256_C_${t}() {\n`;
    circom += `    var C[${totalRounds * t}];\n`;
    for (let r = 0; r < totalRounds; r++) {
      for (let j = 0; j < t; j++) {
        circom += `    C[${r * t + j}] = ${toDecimal(roundConstants[r][j])};\n`;
      }
    }
    circom += `    return C;\n}\n\n`;

    // MDS matrix
    circom += `function POSEIDON_P256_M_${t}() {\n`;
    circom += `    var M[${t}][${t}];\n`;
    for (let i = 0; i < t; i++) {
      for (let j = 0; j < t; j++) {
        circom += `    M[${i}][${j}] = ${toDecimal(mds[i][j])};\n`;
      }
    }
    circom += `    return M;\n}\n\n`;
  }

  return circom;
}

const output = generateCircomConstants();
const outPath = "circuits/components/poseidon_p256_constants.circom";
writeFileSync(outPath, output);
console.log(`Wrote ${outPath}`);
console.log(`Constants generated for P-256 base field (circom secq256r1).`);
