// auto-generated by circomkit
pragma circom 2.2.3;

include "../cert_chain.circom";

component main {public[issuer_rsa_modulus, smtRoot, serialNumber]} = CertChainRSA256(1536, 121, 34, 4096, 17, 2048, 128, 128, 17);
