import { WitnessTester } from "circomkit";
import { circomkit } from "../common";
import { generateJWTRS256CircuitParams, generateJWTRS256Inputs, hashClaim } from "../../src/jwt_rs256";
import * as fs from "fs";
import * as path from "path";

describe("JWT-RS256 Verifier", () => {
  let circuit: WitnessTester<
    [
      "message",
      "messageLength",
      "periodIndex",
      "rsaModulus",
      "rsaSignature",
      "matchesCount",
      "matchSubstring",
      "matchLength",
      "matchIndex",
      "claims",
      "claimLengths",
      "decodeFlags",
      "ageClaimIndex",
      "currentYear",
      "currentMonth",
      "currentDay"
    ],
    ["ageAbove18"]
  >;

  describe("RS256 Age JWT Claim Verification", () => {
    before(async () => {
      const RECOMPILE = true;
      circuit = await circomkit.WitnessTester(`jwt_rs256`, {
        file: "jwt_rs256",
        template: "JWTRS256",
        params: [1920, 1900, 4, 50, 128, 121, 17],
        recompile: RECOMPILE,
      });
      console.log("#constraints:", await circuit.getConstraintCount());
    });

    it("should verify RS256 JWT with valid age claim", async () => {
      // Load test data generated by generate_rsa_jwt.py
      const testDataPath = path.join(__dirname, "../../inputs/jwt_rs256/default.json");

      // Check if test data exists, skip if not
      if (!fs.existsSync(testDataPath)) {
        console.log("Test data not found. Generate it with:");
        console.log("  python ../scripts/generate_rsa_jwt.py --output inputs/jwt_rs256/default.json --circuit-inputs");
        return;
      }

      const testData = JSON.parse(fs.readFileSync(testDataPath, "utf8"));

      try {
        const witness = await circuit.calculateWitness(testData);
        await circuit.expectConstraintPass(witness);

        // Check the output - this may fail due to large symbol table
        try {
          const output = await circuit.readWitnessSignals(witness, ["ageAbove18"]);
          console.log("ageAbove18:", output.ageAbove18);
        } catch (e) {
          // Symbol table too large, but witness calculation succeeded
          console.log("Witness generated successfully (symbol table too large to read outputs)");
        }
      } catch (e) {
        // If witness calculation fails, re-throw the error
        throw e;
      }
    });

    it("should verify RS256 JWT using TypeScript input generator", async () => {
      // This test uses the TypeScript input generator with manually created test data
      // You can replace this with actual RS256 JWT test data

      // Skip if no test JWT is available
      const testJwtPath = path.join(__dirname, "../../test_data/rs256_jwt.json");
      if (!fs.existsSync(testJwtPath)) {
        console.log("TypeScript generator test skipped - no test JWT data");
        return;
      }

      const testJwt = JSON.parse(fs.readFileSync(testJwtPath, "utf8"));

      const params = generateJWTRS256CircuitParams([1920, 1900, 4, 50, 128, 121, 17]);

      // Extract claims from SD-JWT
      const [token, ...claims] = testJwt.sdJwt.split("~");

      // Hash claims for matching
      const hashedClaims = claims.map(hashClaim);

      // Generate decode flags (decode all claims)
      const decodeFlags = claims.map(() => 1);

      const inputs = generateJWTRS256Inputs(
        params,
        token,
        testJwt.rsaPublicKey,
        hashedClaims,
        claims,
        decodeFlags,
        {
          year: new Date().getFullYear(),
          month: new Date().getMonth() + 1,
          day: new Date().getDate(),
        }
      );

      const witness = await circuit.calculateWitness(inputs);
      await circuit.expectConstraintPass(witness);

      const output = await circuit.readWitnessSignals(witness, ["ageAbove18"]);
      console.log("ageAbove18:", output.ageAbove18);
    });
  });
});
