name: circom-tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --yes \
            build-essential \
            libgmp-dev \
            libsodium-dev \
            nasm \
            nlohmann-json3-dev

      - name: Download Circom Binary v2.2.3
        run: |
          wget -qO /home/runner/work/circom https://github.com/iden3/circom/releases/download/v2.2.3/circom-linux-amd64
          chmod +x /home/runner/work/circom
          sudo mv /home/runner/work/circom /bin/circom

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Print Circom version
        run: circom --version

      - name: Install dependencies
        run: cd wallet-unit-poc/circom && yarn

      - name: Compile JWT-RS256 circuit
        run: cd wallet-unit-poc/circom && yarn compile:jwt_rs256

      - name: Run jwt_rs256 end-to-end flow
        run: |
          cd wallet-unit-poc/ecdsa-spartan2
          cargo run --release -- jwt_rs256 setup --input ../circom/inputs/jwt_rs256/default.json
          cargo run --release -- jwt_rs256 prove --input ../circom/inputs/jwt_rs256/default.json
          cargo run --release -- jwt_rs256 verify

      - name: Run circom tests
        run: cd wallet-unit-poc/circom && yarn test tests/circuits/jwt_rs256.test.ts
