name: circom-tests

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest

        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v5

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Install dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install --yes \
                    build-essential \
                    libgmp-dev \
                    libsodium-dev \
                    nasm \
                    nlohmann-json3-dev

            - name: Download Circom Binary v2.2.3
              run: |
                  wget -qO /home/runner/work/circom https://github.com/iden3/circom/releases/download/v2.2.3/circom-linux-amd64
                  chmod +x /home/runner/work/circom
                  sudo mv /home/runner/work/circom /bin/circom

            - name: Set up Rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  override: true

            - name: Print Circom version
              run: circom --version

            - name: Install dependencies
              run: cd wallet-unit-poc/circom && yarn

            - name: Compile RS256 circuit
              run: cd wallet-unit-poc/circom && yarn compile:rs256

            - name: Run rs256 end-to-end flow
              run: |
                  cd wallet-unit-poc/ecdsa-spartan2
                  cargo run --release -- rs256 setup --input ../circom/inputs/rs256/input.json
                  cargo run --release -- rs256 prove --input ../circom/inputs/rs256/input.json
                  cargo run --release -- rs256 verify

            - name: Run ecdsa-spartan2 tests
              run: |
                  cd wallet-unit-poc/ecdsa-spartan2
                  cargo test --release

            - name: Run mopro API tests
              run: |
                  cd wallet-unit-poc/mobile
                  cargo test --release --no-default-features --lib

            - name: Create ZIP of proving key
              run: |
                cd wallet-unit-poc/ecdsa-spartan2/keys
                zip rs256_proving.key.zip rs256_proving.key

            - name: Create ZIP of verifying key
              run: |
                cd wallet-unit-poc/ecdsa-spartan2/keys
                zip rs256_verifying.key.zip rs256_verifying.key

            - name: Create ZIP of R1CS artifact
              run: |
                cd wallet-unit-poc/circom/build/rs256/rs256_js
                zip -r rs256.r1cs.zip rs256.r1cs

            - name: Upload release artifacts
              if: github.event_name == 'push' && github.ref == 'refs/heads/main'
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: latest
                  files: |
                    wallet-unit-poc/ecdsa-spartan2/keys/rs256_proving.key.zip
                    wallet-unit-poc/ecdsa-spartan2/keys/rs256_verifying.key.zip
                    wallet-unit-poc/circom/build/rs256/rs256_js/rs256.r1cs.zip
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
